code/interface/WoW/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from transact import views
urlpatterns = [
    # Examples:
    # url(r'^$', 'WoW.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^transact/',include('transact.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/profile/', views.index,name='index'),
    url('^register/', CreateView.as_view(
            template_name='registration/register.html',
            form_class=UserCreationForm,
            success_url='/'
    ))
    ]

code/interface/transact/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new', views.new_transaction, name='new'),
    url(r'^visualjson', views.visualize_json, name='vjson'),
    url(r'^visual', views.visual, name='visual'),
    url(r'^cvisualjson', views.cvisualize_json, name='cvjson'),
    url(r'^cvisual', views.cvisual, name='cvisual'),
    url(r'^transactions', views.transactions, name='transactions'),
    url(r'^respond', views.respond, name='respond'),
    url(r'^analyze_greedy', views.analyze_greedy, name='analyze_greedy'),
    url(r'^analyze_friendly', views.analyze_friendly, name='analyze_friendly'),
    url(r'^clean', views.clean, name='clean'),
    url(r'^control', views.control, name='control'),
    url(r'^friends', views.friends, name='friends'),
    url(r'^processfriendship', views.processfriendship, name='processfriendship'),
    url(r'^cancelfriendrequest', views.cancelfriendrequest, name='cancelfriendrequest'),
    url(r'^canceltransactionrequest', views.canceltransactionrequest, name='canceltransactionrequest'),
    url(r'^createSampleTransactions', views.createSampleTransactions, name='createSampleTransactions'),
    url(r'^smallCreateTransactions', views.smallCreateTransactions, name='createSampleTransactions'),
    url(r'^createGroups', views.createGroups, name='createGroups'),
    url(r'^profile', views.profile, name='profile')

]

code/interface/transact/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import validate_slug
from django.db.models.signals import post_save

# Create your models here.

#class to add dates to all models
class BaseModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

#profile for keeping track of user information
class Profile(BaseModel):
  friends = models.ManyToManyField("self")
  user = models.ForeignKey(User,related_name='profile')
  description = models.TextField(default="")
  networth = models.IntegerField(default=0)

#this function creates a profile for the user when the user is created
#best way to extend djangos built in user model
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)


class FriendRequest(BaseModel):
  sender = models.ForeignKey(User,related_name='friendor')
  recepient = models.ForeignKey(User,related_name='friendee')



#sender is creditor, recepient is debtor, accepted is 0 for new request 1 if accepted
class Transaction(BaseModel):
   recepient = models.ForeignKey(User,related_name='recepient')
   sender = models.ForeignKey(User,related_name='sender') 
   amount = models.FloatField()
   accepted = models.PositiveIntegerField(default=0)

#transactions after algorithim is run
class CalculatedTransaction(BaseModel):
  recepient = models.ForeignKey(User,related_name='recepientc')
  sender = models.ForeignKey(User,related_name='senderc')
  amount = models.FloatField()

#calculates networth for every user
def update_net_worth(prof):
  user = prof.user
  assets = Transaction.objects.filter(sender=user).filter(accepted=1)
  debts = Transaction.objects.filter(recepient=user).filter(accepted=1)
  nw = 0
  for asset in assets:
    nw += asset.amount
  for debt in debts:
    nw -= debt.amount
  prof.networth = nw
  prof.save()



#calculates networth and analyzes the graph after every transaction
def calculate_net_worth(sender, instance, created, **kwargs):
    update_net_worth(instance.sender.profile.get())
    update_net_worth(instance.recepient.profile.get())

post_save.connect(calculate_net_worth, sender=Transaction)

class TransactionRequest(BaseModel):
  sender = models.ForeignKey(User,related_name='tsender')
  recepient = models.ForeignKey(User,related_name='trecepient')
  transaction = models.ForeignKey(Transaction,related_name='request')
   
class TransactionForm(ModelForm):
    def validate_friend(value):
      users = User.objects.filter(username=value)
      if not users.exists():
        raise ValidationError("User does not exist")
      
    friend = forms.CharField(label='Friend',validators=[validate_slug,validate_friend])
    CHOICES=[('loan','Loan'),
         ('borrow','Borrow')]
    lob = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())
    class Meta:
        model = Transaction
        fields = ['amount']

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ["description"]
      

code/interface/transact/views.py
#some code based off of django documentation

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils import timezone
from transact.models import Profile
from transact.models import ProfileForm
from transact.models import Transaction
from transact.models import CalculatedTransaction
from transact.models import TransactionForm
from transact.models import TransactionRequest
from transact.models import FriendRequest
from django.contrib.auth.models import User 
from django.http import JsonResponse
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.template import RequestContext
from django import forms
import string
import random
from common.util.analyze import Person,GreedyOptimizer
from common.util.friendlyanalyze import FriendlyOptimizer
import time

@login_required
def index(request):
  networth = request.user.profile.get().networth
  if networth > 0:
    computations = CalculatedTransaction.objects.filter(sender=request.user)
  elif networth < 0:
    computations = CalculatedTransaction.objects.filter(recepient=request.user)
  else:
    computations = ""
  return render(request,'index.html',{ 'networth':networth,'computations':computations})

@login_required
def new_transaction(request):
  if request.method == 'POST':
    form = TransactionForm(request.POST)
    if form.is_valid():
      trans = form.save(commit = False)
      tuser = User.objects.filter(username=form.cleaned_data['friend'])
      if tuser.first() == request.user:
        form.add_error("friend","Can't transact with yourself")
        return render(request, 'transact.html', {'form': form})

      #decide whether the current user is borrowing or loaning money
      if form.cleaned_data['lob'] == "loan":
        trans.recepient = tuser.first()
        trans.sender = request.user
      else:
        trans.recepient = request.user
        trans.sender = tuser.first()
      trans.save()

      #we must save the manytomany relationships seperatly!
      form.save_m2m()

      #create a transactionrequest pending approval
      TransactionRequest.objects.create(sender=request.user,recepient=tuser.first(),transaction=trans)
      return HttpResponseRedirect('/transact/transactions')

  else:
      form = TransactionForm()

  return render(request, 'transact.html', {'form': form})

@login_required
def profile(request):
  if request.method == 'POST':
      form = ProfileForm(data=request.POST,instance=request.user.profile.get())
      if form.is_valid():
        form.save()
        form = ProfileForm(instance=request.user.profile.get())
  else:
    form = ProfileForm(instance=request.user.profile.get())
  return render(request,"profile.html",{'form':form})

@login_required
def transactions(request):
  pendingts = TransactionRequest.objects.filter(recepient=request.user)
  sentts = TransactionRequest.objects.filter(sender=request.user)
  acceptedts = Transaction.objects.filter(Q(sender=request.user)|Q(recepient=request.user)).filter(accepted=1)      

  return render(request, 'transactions.html', {'acceptedts':acceptedts, 'pendingts':pendingts, 'sentts':sentts},context_instance=RequestContext(request))
  
@login_required
def canceltransactionrequest(request):
  tr = TransactionRequest.objects.filter(id=request.GET.get('id','-1'))

  #check if user maliciously changed get request
  if not tr.exists():
    messages.add_message(request, messages.WARNING, 'Error')
    return HttpResponseRedirect('transactions')

  trr = tr.first()
  if not (trr.sender == request.user):
    messages.add_message(request, messages.WARNING, 'Error')
    return HttpResponseRedirect('transactions')
  
  trr.transaction.delete()
  trr.delete()
  
  return HttpResponseRedirect('transactions')

@login_required
def respond(request):
  tr = TransactionRequest.objects.filter(id=request.GET.get('id','-1'))
  if not tr.exists():
    messages.add_message(request, messages.WARNING, 'Error')
    return HttpResponseRedirect('transactions')
  trr = tr.first()
  if not (trr.recepient == request.user):
    messages.add_message(request, messages.WARNING, 'Error')
    return HttpResponseRedirect('transactions')

  if request.GET.get('c','-1') == "accept":
    trans = trr.transaction
    #mark as accepted
    trans.accepted = 1
    trans.save()
    trr.delete()
    #have users friend eachother and check if friendrequests exist and clear them 
    if not trr.recepient.profile.get().friends.filter(id=trr.sender.profile.get().id).exists():
        posssend = FriendRequest.objects.filter(sender=trr.sender).filter(recepient=trr.recepient)
        possrecep = FriendRequest.objects.filter(sender=trr.recepient).filter(recepient=trr.sender)
        if posssend.exists():
          posssend.get().delete()
        if possrecep.exists():
          possrecep.get().delete()
        trr.recepient.profile.get().friends.add(trr.sender.profile.get())

  elif request.GET.get('c','-1') == "reject":
    trr.transaction.delete()
    trr.delete()
  else:
    messages.add_message(request, messages.WARNING, 'Error')
  
  return HttpResponseRedirect('transactions')

class NewFriendForm(forms.Form):
  username = forms.CharField(label='Username:')

@login_required
def friends(request):
  myfriends = request.user.profile.get().friends
  requests = request.user.friendee
  myasks = request.user.friendor
  
  if request.method == 'POST':
    form = NewFriendForm(request.POST)
    if form.is_valid():
      usern = form.cleaned_data['username']
      friend = User.objects.filter(username=usern)
      if friend.first() == request.user:
        form.add_error("username","Can't friend yourself")
        return render(request,'friends.html', {'myfriends':myfriends,'requests':requests,'myasks':myasks, 'form':form},context_instance=RequestContext(request))

      if friend.exists():
        if not request.user.profile.get().friends.filter(id=friend.get().profile.get().id).exists():
          posssend = FriendRequest.objects.filter(sender=request.user).filter(recepient=friend.get()).exists()
          possrecep = FriendRequest.objects.filter(sender=friend.get()).filter(recepient=request.user).exists()
          if not (posssend or possrecep):
              
            FriendRequest.objects.create(sender = request.user, recepient=friend.get())
            form = NewFriendForm()
          else:
            form.add_error('username', "Pending request already")
        else:
          form.add_error('username', "Already friends")
      else:
        form.add_error('username', "User doesn't exist")
      

  else:
      form = NewFriendForm()
    
  return render(request,'friends.html',{'myfriends':myfriends,'requests':requests,'myasks':myasks, 'form':form},context_instance=RequestContext(request))

@login_required
def cancelfriendrequest(request):
    frr = FriendRequest.objects.filter(id=request.GET.get('id','-1'))
    if not frr.exists():
      messages.add_message(request, messages.WARNING, 'Error')
      return HttpResponseRedirect('friends')
    fr = frr.first()
    if not (fr.sender == request.user):
      messages.add_message(request, messages.WARNING, 'Error')
      return HttpResponseRedirect('friends')
    fr.delete()
    return HttpResponseRedirect('friends')
 
@login_required   
def processfriendship(request):
  frr = FriendRequest.objects.filter(id=request.GET.get('id','-1'))
  if not frr.exists():
    messages.add_message(request, messages.WARNING, 'Error')
    return HttpResponseRedirect('friends')
  fr = frr.first()
  if not (fr.recepient == request.user):
    messages.add_message(request, messages.WARNING, 'Error')
    return HttpResponseRedirect('friends')
  if request.GET.get('c','-1') == "accept":
    friends = request.user.profile.get().friends
    friends.add(fr.sender.profile.get())
    fr.delete()
  elif request.GET.get('c','-1') == "reject":
    fr.delete()
  else:
    messages.add_message(request, messages.WARNING, 'Error')
  
  return HttpResponseRedirect('friends')

@login_required
def visualize_json(request):
  users = User.objects.all()
  nodes = []
  links = []
  uids = []
  for user in users:
    #build nodes for graph
    nodes.append({"name":user.username,"networth":user.profile.get().networth})
    #keep uids so we can look up the order to provide the proper data for the js library
    uids.append(user.id)

  #build links  
  for trans in Transaction.objects.filter(accepted=1):
    links.append({"source":uids.index(trans.sender.id), "target":uids.index(trans.recepient.id)})
    
  return JsonResponse({"nodes":nodes,"links":links})

@login_required
def visual(request):
  return render(request, 'visual.html')

#see visualize_json
@login_required
def cvisualize_json(request):
  users = User.objects.all()
  nodes = []
  links = []
  uids = []
  for user in users:
    nodes.append({"name":user.username,"networth":user.profile.get().networth})
    uids.append(user.id)
  for trans in CalculatedTransaction.objects.all():
    links.append({"source":uids.index(trans.sender.id), "target":uids.index(trans.recepient.id)})
    
  return JsonResponse({"nodes":nodes,"links":links})

@login_required
def cvisual(request):
  return render(request, 'cvisual.html')

#makes a simple set of transactions where one user gives two users two dollars each who then give a fourth user 10 dollars each
#the algorithm should bypass the two users inbetween the fourth and first user

def createUsers(num):
  users = []
  for i in range(num):
    name = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(5))
    users.append(User.objects.create(username=name,password=name))

  return users


def createGroup():
  users = createUsers(10)
  for user in users:
    for user2 in users:
      if not user.profile.get().friends.filter(id=user2.profile.get().id).exists():
        user.profile.get().friends.add(user2.profile.get())
  for user in users:

code/interface/transact/templates/base.html
<html>
  <head>
  <script src="http://cdn.jsdelivr.net/jquery/2.1.4/jquery.js"></script>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.4.1/d3.min.js"></script>
    <script src="/static/scripts.js"></script>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/style.css">
    <script>
      {% block script %}
      {% endblock %}
    </script>
    <style>

.node {
  stroke: #fff;
  stroke-width: 1.5px;
}

.link {
  stroke: #999;
  stroke-opacity: .6;
}

</style>

  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
<html>

code/interface/transact/templates/basetrans.html
{% extends "base.html" %}

{% block content %}
	<div id = "maincon" class = "container">

		<div class="row">
			<div class="col-12 col-sm-2 col-lg-2 left">
				<ul class="nav nav-pills nav-stacked">
  					<li role="presentation" ><a href = "/transact/">Home</a></li>
  					<li role="presentation" ><a href = "/transact/new">New Transaction</a></li>
  					<li role="presentation" ><a href = "/transact/transactions">Transaction History</a></li>

  					<li role="presentation" ><a href = "/transact/profile">Profile</a></li>
  					<li role="presentation" ><a href = "/transact/friends">Manage Friends</a></li>
  					<li role="presentation" ><a href = "/transact/visual">Graph View</a></li>
  					<li role="presentation" ><a href = "/transact/cvisual">Computed Graph View</a></li>
  					<li role="presentation" ><a href = "/transact/control">Control</a></li>

				</ul>

			</div>

			<div id = "content" class="col-12 col-sm-8 col-lg-8 main">
				{% block maincontent %}
				{% endblock %}
			</div>
		</div>  
		<button type="button" id = "logout" class="btn btn-default btn-lg">
  			<span class="glyphicon glyphicon-off" aria-hidden="true"></span> 
  		</button>
	</div>
{% endblock %}

code/interface/transact/templates/control.html
{% extends "basetrans.html" %}
{% load myfilters %}

{% block title %} Control {% endblock %}

{% block maincontent %}
	<div style = "padding-top:30px">
    	<button type="button" class="btn btn-default" onclick ="document.location.href = '/transact/analyze_greedy'">Analyze Greedy</button>
    	<button type="button" class="btn btn-default" onclick ="document.location.href = '/transact/analyze_friendly'">Analyze Friendly</button>
    	<button type="button" class="btn btn-default" onclick ="document.location.href = '/transact/clean'">Reset</button>
    	<button type="button" class="btn btn-default" onclick ="document.location.href = '/transact/smallCreateTransactions'">Simplest Example</button>
    	<button type="button" class="btn btn-default" onclick ="document.location.href = '/transact/createSampleTransactions'">Random Example</button>
    	<button type="button" class="btn btn-default" onclick ="document.location.href = '/transact/createGroups'">Friend Group Example</button>


    </div>
{% endblock %}

code/interface/transact/templates/cvisual.html
{% extends "basetrans.html" %}
{% load myfilters %}
{% block title %} Visual {% endblock %}
{% block script %} 


{% endblock %}
{% block maincontent %}
<script>
/*d3.json("visualjson", function(error, graph) {
console.log(graph.nodes);
console.log(graph.links);
var vis = d3.select("body")
            .append("svg");
     var w = 200,
         h = 200;
     vis.attr("width", w)
        .attr("height", h);
     vis.text("Our Graph")
        .select("#graph");
     var force = d3.layout.force()
    .nodes(graph.nodes)
    .links(graph.links)
    .size([w, h])
    .linkStrength(0.1)
    .friction(0.9)
    .linkDistance(20)
    .charge(-30)
    .gravity(0.1)
    .theta(0.8)
    .alpha(0.1)
    .start();
    
});*/

var width = 900,
    height = 500;

var color = d3.scale.category20();

var force = d3.layout.force()
    .charge(-120)
    .linkDistance(30)
    .size([width, height]);

var svg = d3.select("#content").append("svg")
    .attr("width", width)
    .attr("height", height);

d3.json("cvisualjson", function(error, graph) {
  force
      .nodes(graph.nodes)
      .links(graph.links)
      .start();

  var link = svg.selectAll(".link")
      .data(graph.links)
    .enter().append("line")
      .attr("class", "link")
      .style("stroke-width", function(d) { return Math.sqrt(d.value); });

  var node = svg.selectAll(".node")
      .data(graph.nodes)
    .enter().append("circle")
      .attr("class", "node")
      .attr("r", 5)
      .style("fill", function(d) { return color(d.group); })
      .call(force.drag)
      .on("mouseover", function(d)
 {
      $("#placeholder").text("Name: " +d.name + " NW: " + d.networth)
 })
.on("mouseout", function(d)
 {
          $("#placeholder").text("")

 });

  node.append("title")
      .text(function(d) { return d.name; });

  force.on("tick", function() {
    link.attr("x1", function(d) { return d.source.x; })
        .attr("y1", function(d) { return d.source.y; })
        .attr("x2", function(d) { return d.target.x; })
        .attr("y2", function(d) { return d.target.y; });

    node.attr("cx", function(d) { return d.x; })
        .attr("cy", function(d) { return d.y; });
  });
});

</script>
<div id ="placeholder"></div>
{% endblock %}

code/interface/transact/templates/friends.html
{% extends "basetrans.html" %}
{% load myfilters %}

{% block title %} Friends {% endblock %}

{% block maincontent %}

    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
    
<form action="{{ action }}" method="POST">
  {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
                     {% if form.username.errors %}
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
         {{ form.username.errors }}
        </div>
        {% endif %}
        <label for="id_username">Username:</label>
        {{ form.username|addcss:'form-control' }}
    </div>
                    <button type="submit" class="btn btn-default">Add Friend</button>
</form>

Friends:
  <table class = "table">
    <tr>
      <th>Name</th>
    </tr>
    {% for friend in myfriends.all %}
      <tr><td><span class="pop" data-toggle="popover" data-trigger="hover" title="{{ friend.user.username }}" data-content= "{{friend.description}}">{{ friend.user.username }}</span></td></tr>
    {% endfor %}
  </table>
  
Requests:
  <table class = "table">
    <tr>
      <th>Name</th>
      <th>Accept</th>
      <th>Reject</th>
    </tr>
    {% for friend in requests.all %}
      <tr>
        <td>{{ friend.sender.username }}</td>
        <td><a href = "processfriendship?c=accept&id={{friend.id}}"><span class="glyphicon glyphicon-ok-sign"></span></a></td>
        <td><a href = "processfriendship?c=reject&id={{friend.id}}"><span class="glyphicon glyphicon-remove-sign"></span></a></td>
      </tr>
    {% endfor %}
  </table>

Your requests:
  <table class = "table">
    <tr>
      <th>Name</th>
      <th>Cancel</th>
    </tr>
    {% for friend in myasks.all %}
      <tr>
        <td>{{ friend.recepient.username }}</td>
        <td><a href = "cancelfriendrequest?id={{friend.id}}"><span class="glyphicon glyphicon-remove-sign"></span></a></td>
      </tr>
    {% endfor %}
  </table>

{% endblock %}

code/interface/transact/templates/index.html
{% extends "basetrans.html" %}
{% load myfilters %}

{% block title %} Home {% endblock %}
{% block maincontent %}

<h1> Your networth is: {{networth}} </h1>

{% if networth > 0 %}
	These people owe you money.
{% elif networth < 0 %}
	You owe these people money.
{% else %}
	Make some transactions.
{% endif %}
  {% if networth != 0 %}
  <table class = "table">
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Amount</th>
    </tr>
    {% for trans in computations %}
      <tr>
      	<td><span class="pop" data-toggle="popover" data-trigger="hover" title="{{ trans.sender.username }}" data-content= "{{trans.sender.username}}">{{ trans.sender.username }}</span></td>
      	      	<td><span class="pop" data-toggle="popover" data-trigger="hover" title="{{ trans.recepient.username }}" data-content= "{{trans.recepient.username}}">{{ trans.recepient.username }}</span></td>

      	<td>{{trans.amount}}</td>
      </tr>
    {% endfor %}
  </table>
  {% endif %}
{% endblock %}

code/interface/transact/templates/profile.html
{% extends "basetrans.html" %}
{% load myfilters %}

{% block title %} Profile {% endblock %}
{% block maincontent %}
<h3>Provide some information for communication to exchange money.</h3>
<form action="{{ action }}" method="POST">
  {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
                     {% if form.description.errors %}
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
         {{ form.description.errors }}
        </div>
        {% endif %}
        <label for="id_description"></label>

            {{ form.description|addcss:'form-control' }}
    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
</form>

{% endblock %}

code/interface/transact/templates/transact.html
{% extends "basetrans.html" %}
{% load myfilters %}

{% block title %} Transact {% endblock %}
{% block maincontent %}
<form action="{{ action }}" method="POST">
  {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
        <div id = "lobcontainer">
                     {% if form.lob.errors %}
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
         {{ form.lob.errors }}
        </div>
        {% endif %}
        <label for="id_lob"></label>

            {{ form.lob|addcss:'form-control' }}
        </div>
    </div>
    <div class="form-group">
                 {% if form.amount.errors %}
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
         {{ form.amount.errors }}
        </div>
        {% endif %}

        <label for="id_amount">Amount:</label>
        {{ form.amount|addcss:'form-control' }}
    </div>
    <div class="form-group">
                 {% if form.friend.errors %}
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
         {{ form.friend.errors }}
        </div>
        {% endif %}

        <label for="id_friend">Friend:</label>
        {{ form.friend|addcss:'form-control' }}
    </div>


                    <button type="submit" class="btn btn-default">Submit</button>
</form>
{% endblock %}

code/interface/transact/templates/transactions.html
{% extends "basetrans.html" %}
{% load myfilters %}
{% block title %} Transactions {% endblock %}
{% block maincontent %}
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}

Transaction Requests:
  <table class = "table">
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Amount</th>
      <th>Accept</th>
      <th>Reject</th>
    </tr>
    {% for trequest in pendingts %}
        <tr>
            <td>{{trequest.transaction.sender.username}}</td>
            <td>{{trequest.transaction.recepient.username}}</td>
            <td>{{trequest.transaction.amount}}</td>
            <td><a href = "respond?c=accept&id={{ trequest.id }}"><span class="glyphicon glyphicon-ok-sign"></span></a></td>
            <td><a href = "respond?c=reject&id={{ trequest.id }}"><span class="glyphicon glyphicon-remove-sign"></span></td>
        </tr>

    {% endfor %}
  </table>

  Sent pending transactions:
  <table class = "table">
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Amount</th>
      <th>Cancel</th>
    </tr>
    {% for trequest in sentts %}
        <tr>
            <td>{{trequest.transaction.sender.username}}</td>
            <td>{{trequest.transaction.recepient.username}}</td>
            <td>{{trequest.transaction.amount}}</td>
            <td><a href = "canceltransactionrequest?id={{ trequest.id }}"><span class="glyphicon glyphicon-remove-sign"></span></a></td>
        </tr>

    {% endfor %}
  </table>

  Transaction History:
  <table class = "table">
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Amount</th>
    </tr>
    {% for trans in acceptedts %}
        <tr>
            <td>{{trans.sender.username}}</td>
            <td>{{trans.recepient.username}}</td>
            <td>{{trans.amount}}</td>
        </tr>

    {% endfor %}
  </table>



{% endblock %}